version: '3.9'
services:
  app:
    container_name: football_hub_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    env_file:
      - .env.development
    command: npm run dev

  db:
    image: postgres:15
    container_name: football_hub_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football_hub
    ports:
      - '5433:5432'
    volumes:
      - football_hub_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: football_hub_redis
    ports:
      - '6379:6379'

volumes:
  football_hub_db_data:
